services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - .:/app  # Mount the current directory into /app for live code changes
      - ./static:/app/static
      - ./media:/app/media
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.develop
    ports:
      - "8020:8020"

  # nginx:
  #   image: nginx:alpine
  #   restart: always
  #   depends_on:
  #     - web
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf
  #     - static_volume:/app/static
  #     - media_volume:/app/media
  #     - .:/app  # Share the code with nginx for access to static files during development

volumes:
  static_volume:
  media_volume: 