# Generated by Django 5.2.1 on 2025-05-14 07:40

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('link_type', models.CharField(choices=[('object', 'Django model instance'), ('route', 'Named URL pattern'), ('external', 'External / hard‑coded URL')], default='object', max_length=8)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('route_name', models.CharField(blank=True, max_length=200)),
                ('route_kwargs', models.JSONField(blank=True, default=dict)),
                ('external_url', models.CharField(blank=True, max_length=500)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.menuitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
