# Generated by Django 5.2.1 on 2025-05-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menuitem_delete_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='link_type',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='route_kwargs',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='route_name',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='url',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
