# Generated by Django 5.2.1 on 2025-05-14 10:40

import apps.utils.mixins
from django.db import migrations, models
from tinymce.models import HTMLField

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_menuitem_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', HTMLField()),
                ('short_description', HTMLField()),
                ('founded_year', models.SmallIntegerField()),
                ('capacity', models.IntegerField()),
                ('student_count', models.IntegerField()),
                ('teacher_count', models.IntegerField()),
                ('direction_count', models.IntegerField()),
                ('class_count', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('instagram_link', models.URLField()),
                ('telegram_link', models.URLField()),
                ('facebook_link', models.URLField()),
                ('youtube_link', models.URLField()),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.utils.mixins.SlugifyMixin, models.Model),
        ),
    ]
