# Generated by Django 5.2.1 on 2025-06-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_banner_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='banner',
            name='unique_banner_school_title',
        ),
        migrations.RemoveConstraint(
            model_name='banner',
            name='unique_banner_school_title-title_uz',
        ),
        migrations.RemoveConstraint(
            model_name='banner',
            name='unique_banner_school_title-title_ru',
        ),
        migrations.RemoveConstraint(
            model_name='banner',
            name='unique_banner_school_title-title_en',
        ),
        migrations.RemoveConstraint(
            model_name='direction',
            name='unique_direction_slug',
        ),
        migrations.RemoveConstraint(
            model_name='faq',
            name='unique_faq_school_title',
        ),
        migrations.RemoveConstraint(
            model_name='faq',
            name='unique_faq_school_title-title_uz',
        ),
        migrations.RemoveConstraint(
            model_name='faq',
            name='unique_faq_school_title-title_ru',
        ),
        migrations.RemoveConstraint(
            model_name='faq',
            name='unique_faq_school_title-title_en',
        ),
        migrations.RemoveConstraint(
            model_name='musicalinstrument',
            name='unique_musicalinstrument_slug',
        ),
        migrations.RemoveConstraint(
            model_name='schoollife',
            name='unique_schoollife_school_title',
        ),
        migrations.RemoveConstraint(
            model_name='schoollife',
            name='unique_schoollife_school_title-title_uz',
        ),
        migrations.RemoveConstraint(
            model_name='schoollife',
            name='unique_schoollife_school_title-title_ru',
        ),
        migrations.RemoveConstraint(
            model_name='schoollife',
            name='unique_schoollife_school_title-title_en',
        ),
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_subject_slug',
        ),
        migrations.AlterField(
            model_name='direction',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='musicalinstrument',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
